apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
  namespace: default
spec:
  type: NodePort    
  ports:
  - ports: 80
    protocol: TCP
    targetPort: 80
  selector: 
    run: nginx-service
